# Generated by Django 4.2.23 on 2025-08-15 18:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Набор моделей', max_length=100)),
                ('description', models.CharField(default='Описание набора моделей', max_length=1000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incomes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnitModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('users', models.IntegerField(default=0)),
                ('customers', models.IntegerField(default=0)),
                ('AVP', models.IntegerField(default=0)),
                ('APC', models.IntegerField(default=0)),
                ('TMS', models.IntegerField(default=0)),
                ('COGS', models.IntegerField(default=0)),
                ('COGS1s', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('model_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_combination', to='api.modelset')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='single_combination', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'модель юнит-экономики',
                'verbose_name_plural': 'модели юнит-экономики',
            },
        ),
    ]
