# Generated by Django 4.2.23 on 2025-08-19 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_unitmodel_fc'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmodel',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
