# Generated by Django 4.2.23 on 2025-08-23 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0003_unitmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='unitmodel',
            name='AGR',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unitmodel',
            name='RR',
            field=models.IntegerField(default=100),
        ),
        migrations.AlterField(
            model_name='unitmodel',
            name='model_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='api.modelset'),
        ),
        migrations.AlterField(
            model_name='unitmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sets', to=settings.AUTH_USER_MODEL),
        ),
    ]
