# Generated by Django 4.2.23 on 2025-08-23 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_unitmodel_agr_unitmodel_rr_alter_unitmodel_model_set_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unitmodel',
            name='AGR',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='unitmodel',
            name='RR',
            field=models.FloatField(default=1),
        ),
    ]
