{
 "title": "Unit economics bot dashboard",
 "time": { "from": "2025-08-27T00:00:00.000Z", "to": "2025-08-29T00:00:00.000Z" },
 "panels": [
  {
   "title": "Total logs",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COUNT(*) as logs\nFROM logs_database.logs\n"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    COALESCE(SUM(cnt), 0) AS total_errors\nFROM (\n    SELECT\n        response_code,\n        count(*) AS cnt\n    FROM logs_database.logs\n    WHERE response_code >= 400\n    GROUP BY response_code\n) AS count_table"
    }
   ]
  },
  {
   "title": "Logs levels time series",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfHour(timestamp) AS ts,\n    level,\n    count(*) AS cnt\nFROM logs_database.logs\nGROUP BY ts, level\nORDER BY ts, level"
    }
   ]
  },
  {
   "title": "Platform load",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\n    platform,\n    count(*) AS cnt\nFROM logs_database.logs\nGROUP BY platform\nORDER BY cnt DESC"
    }
   ]
  },
  {
   "title": "Request Methods statistics",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    request_method,\n    count(*) AS requests\nFROM logs_database.logs\nGROUP BY request_method\nORDER BY requests DESC"
    }
   ]
  },
  {
   "title": "User Churn",
   "type": "timeseries",
   "description": "The churn of users in the current period",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "rawSql": "SELECT\n    today.day AS day,\n    countIf(prev_active = 1 AND today_active = 0) AS churned_users\nFROM\n(\n    SELECT\n        user_id,\n        toStartOfDay(timestamp) AS day,\n        1 AS today_active\n    FROM logs_database.logs\n    WHERE is_authenticated = 1\n) AS today\nANY LEFT JOIN\n(\n    SELECT\n        user_id,\n        toStartOfDay(timestamp) AS day,\n        1 AS prev_active\n    FROM logs_database.logs\n    WHERE is_authenticated = 1\n) AS yesterday\nON today.user_id = yesterday.user_id AND today.day = yesterday.day + 1\nGROUP BY day\nORDER BY day"
    }
   ]
  },
  {
   "title": "DAU",
   "type": "timeseries",
   "description": "Daily Active Users",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfDay(timestamp) AS day,\n    countDistinct(user_id) AS active_users\nFROM logs_database.logs\nWHERE is_authenticated = 1\nGROUP BY day\nORDER BY day"
    }
   ]
  },
  {
   "title": "New users",
   "type": "timeseries",
   "description": "The income of new users",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfDay(timestamp) AS day,\n    countDistinct(user_id) AS new_users\nFROM logs_database.logs\nWHERE is_authenticated = 1\nGROUP BY day\nORDER BY day"
    }
   ]
  },
  {
   "title": "Total actions",
   "type": "timeseries",
   "description": "Временной ряд действий",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfHour(timestamp) AS ts,\n    count(*) AS actions_count\nFROM logs_database.logs\nGROUP BY ts\nORDER BY ts"
    }
   ]
  },
  {
   "title": "Action type statistics",
   "type": "barchart",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT\n    action,\n    count(*) AS type\nFROM logs_database.logs\nGROUP BY action\nORDER BY type DESC"
    }
   ]
  }
 ]
}