# Generated by Django 4.2.23 on 2025-08-27 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='test_group',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
